### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by uekichinos** [MinerGate/minergate-api#1]
Im not sure what went wrong and I can confirm my credential is valid but when I try this API URL "https://api.minergate.com/1.0/auth/login" I'm getting error as below which wasn't in your description.

{"error":"MissingEmail","argument":"email","message":"User email must be specified."}

FYI, I didnt enable 2-step authorization so I guess passing empty value to parameter 'totp' is ok?

**Comment by uekichinos** [comment]
nevermind. its okey now. manage to get the token.

**Comment by MinerGate** [comment]
Hello,

Is everything okay now, have you been able to perform what you wanted?

Best regards,
Janika

**Comment by uekichinos** [comment]
Hello,

All good here. Thanks.

**Comment by stpaxoliydina66** [comment]
To recover your password please fill in the email you used to login  ----enter email address------------Email is invalid  ??????????????????????????????????? Year address was normal.
