### ISSUE TITLE
How to get Balance?

### ISSUE THREAD

**Issue by IDLOCKED** [MinerGate/minergate-api#10]
https://minergate.com/api/1.0/balance
The above URL will be 404.
Is there an API that refers to the amount I have?

**Comment by amahlaka** [comment]
How are you trying to retrieve the balances?
not by just clicking the link i assume.
that api function requires you to include your token in the request headers

**Comment by IDLOCKED** [comment]
@amahlaka 
Thank you for your reply.
I want to know the amount of each coin I own (https://minergate.com/internal).
For that purpose I attached a token to the header and executed this API (1.0 / balance), it will be 404.
Is there any other way?

**Comment by amahlaka** [comment]
Did you use Host: https://api.minergate.com or Host: https://minergate.com

**Comment by IDLOCKED** [comment]
@amahlaka 
Wow, I was able to get the amount in this API.
Thank you very much.

https://api.minergate.com/1.0/balance
```
{
"bcn": "0",
"eth": "0",
"fcn": "0",
"aeon": "0",
"btc": "0",
"dsh": "0",
"etc": "0",
"inf8": "0",
"ltc": "0",
"mcn": "0",
"qcn": "0",
"zec": "0",
"xdn": "0",
"xmr": "0"
}
```
