### ISSUE TITLE
InternalError /1.0/auth/login

### ISSUE THREAD

**Issue by chrisdlangton** [MinerGate/minergate-api#13]
POST /1.0/auth/login HTTP/1.1
Host: api.minergate.com
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 0e9fc3e0-c966-f2fb-8d6d-746834825d8e

included totp
email was chrislangton84 "at" gmail "d" com

response;
```
{
    "code": "InternalError",
    "message": "Cannot read property 'send' of undefined"
}
```

should work with any other credentials if it is a code error as it appears to be;

```
curl -X POST \
  https://api.minergate.com/1.0/auth/login \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{
  "email": "your_email@gmail.com",
  "password": "yours here",
  "totp": 123456
}'
```

**Comment by pgiguere1** [comment]
API 1.0 is no longer functional. You have to use 2.x which is undocumented and not meant for public use.

You may look at other issues for help with that, but honestly probably not worth the hassle. You're supposed to provide a captcha so your login process will be limited. And whatever app you build may break at any moment whenever Minergate disables older API versions without warning.

This GitHub should have been closed a while ago. It was originally made for a contest MinerGate had 2 years ago and it seems they had no interest in maintaining it after that.
