### ISSUE TITLE
Is the API service stop running

### ISSUE THREAD

**Issue by pedxyuyuko** [MinerGate/minergate-api#17]
Information:
> time: 2019-5-18 19:52:53
> use Insomnia to test API 

When I try to use any API, there is a message that always show up.
```Json 
{
  "error": "ApiDiscontinued",
  "message": ""
}
```

Is the API service stop running? 

Thanks.

**Comment by ghost** [comment]
yes. the devs have stopped the support for this api. I think its because its not worth the money.

**Comment by pedxyuyuko** [comment]
> yes. the devs have stopped the support for this api. I think its because its not worth the money.

Ohhhhhh.... So sad. Thanks for comment.
